baseurl = "https://alkoding.com/"
title = "Alkoding"
copyright = "Copyright &copy; 2017 - Hammas Hamzah Kuddah"
canonifyurls = true

theme = "casper-two"

disqusShortname = "alkoding"
googleAnalytics = "UA-115608528-1"

paginate = 3

summaryLength = 30
enableEmoji = true

pygmentsCodeFences = true

[author]
  name = "Hammas Hamzah Kuddah"
  email = "hammas.hamzah@gmail.com"
  github = "hammashamzah"
  linkedin = "hammashamzah"
  twitter = "hammashamzah"

[params]
  title = "Alkoding.com"
  tagline = "Teknologi, Lifestyle, Design, Tips dan Trik"
  fbName = "alkoding"
  twitterName = "alkoding"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Teknologi"
  url = "/tags/teknologi/"
  weight = 100

[[menu.main]]
  name = "Lifestyle"
  url = "/tags/lifestyle/"
  weight = 100

[[menu.main]]
  name = "Design"
  url = "/tags/golang/"
  weight = 100